# Generated by Django 5.2.4 on 2025-07-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageobject',
            name='ich_domain',
            field=models.CharField(choices=[('oral', 'Oral Traditions'), ('arts', 'Performing Arts'), ('rituals', 'Social Practices & Rituals'), ('knowledge', 'Knowledge about Nature'), ('crafts', 'Traditional Craftsmanship')], default='oral', max_length=50),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='object_type',
            field=models.CharField(choices=[('tool', 'Tool'), ('vessel', 'Vessel'), ('textile', 'Textile'), ('jewellery', 'Jewellery'), ('architecture', 'Architecture Element')], default='tool', max_length=50),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='origin_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='region',
            field=models.CharField(choices=[('riyadh', 'Riyadh'), ('makkah', 'Makkah'), ('madinah', 'Madinah'), ('qassim', 'Qassim'), ('eastern', 'Eastern Province'), ('asir', 'Asir'), ('tabuk', 'Tabuk'), ('hail', 'Hail'), ('northern', 'Northern Borders'), ('jazan', 'Jazan'), ('najran', 'Najran'), ('bahah', 'Al Bahah'), ('jouf', 'Al Jouf')], default='riyadh', max_length=50),
        ),
    ]
