# Generated by Django 4.2.23 on 2025-08-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_heritageobject_ich_domain_heritageobject_object_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageobject',
            name='accession_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='alternate_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='attribution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='collection_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='See more items in'),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='collector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='copy_after',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='credit_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='data_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='date_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='dimensions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='exhibition_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='field_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='guid',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='maker',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Maker / Artist'),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='materials',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='metadata_usage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='object_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='on_view_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='On View / Location'),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='origin_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='provenance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='record_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='related_resource',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='rights',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Restrictions & Rights'),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='site_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='sitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='taxon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Taxonomy'),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
