# Generated by Django 4.2.23 on 2025-08-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_heritageobject_accession_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritageobject',
            name='ich_domain',
            field=models.CharField(choices=[('oral', 'Oral Traditions'), ('arts', 'Performing Arts'), ('rituals', 'Social Practices & Rituals'), ('knowledge', 'Knowledge about Nature'), ('crafts', 'Traditional Craftsmanship')], default='oral', max_length=50, verbose_name='ICH Domain'),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='models/', verbose_name='Model 3D'),
        ),
    ]
