# Generated by Django 4.2.23 on 2025-08-22 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive', '0004_alter_heritageobject_ich_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritageobject',
            name='object_type',
            field=models.CharField(choices=[('tool', 'Tool'), ('vessel', 'Vessel'), ('textile', 'Textile'), ('jewellery', 'Jewellery'), ('furniture', 'Furniture'), ('ceramic', 'Ceramic'), ('musical instrument', 'Musical Instrument'), ('architecture', 'Architecture'), ('manuscript', 'Manuscript'), ('other', 'Other'), ('architecture_element', 'Architecture Element')], default='tool', max_length=50),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('region', models.CharField(choices=[('riyadh', 'Riyadh'), ('makkah', 'Makkah'), ('madinah', 'Madinah'), ('qassim', 'Qassim'), ('eastern', 'Eastern Province'), ('asir', 'Asir'), ('tabuk', 'Tabuk'), ('hail', 'Hail'), ('northern', 'Northern Borders'), ('jazan', 'Jazan'), ('najran', 'Najran'), ('bahah', 'Al Bahah'), ('jouf', 'Al Jouf')], max_length=50)),
                ('object_type', models.CharField(choices=[('tool', 'Tool'), ('vessel', 'Vessel'), ('textile', 'Textile'), ('jewellery', 'Jewellery'), ('furniture', 'Furniture'), ('ceramic', 'Ceramic'), ('musical instrument', 'Musical Instrument'), ('architecture', 'Architecture'), ('manuscript', 'Manuscript'), ('other', 'Other'), ('architecture_element', 'Architecture Element')], max_length=50)),
                ('ich_domain', models.CharField(choices=[('oral', 'Oral Traditions'), ('arts', 'Performing Arts'), ('rituals', 'Social Practices & Rituals'), ('knowledge', 'Knowledge about Nature'), ('crafts', 'Traditional Craftsmanship')], max_length=50)),
                ('origin_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='submissions/images/')),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='submissions/models/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('data', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='archive.heritageobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='archive.heritageobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeritageLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='archive.heritageobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'object'], name='archive_her_user_id_2cdab0_idx')],
                'unique_together': {('user', 'object')},
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='archive.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'comment'], name='archive_com_user_id_c1b106_idx')],
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
