# Generated by Django 4.2.23 on 2025-08-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_alter_heritageobject_object_type_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
