# Generated by Django 4.2.23 on 2025-08-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageobject',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (Arabic)'),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title (English)'),
        ),
    ]
