# Generated by Django 4.2.23 on 2025-08-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_heritageobject_title_ar_alter_heritageobject_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageobject',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description (French)'),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (French)'),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='description',
            field=models.TextField(verbose_name='Description (English)'),
        ),
    ]
