# Generated by Django 4.2.23 on 2025-08-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_heritageobject_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='alternate_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='attribution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description (French)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='dimensions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='maker',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Maker / Artist'),
        ),
        migrations.AddField(
            model_name='submission',
            name='materials',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='origin_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (Arabic)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (French)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title (English)'),
        ),
    ]
