# Generated by Django 5.1.4 on 2025-08-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_submission_alternate_name_submission_attribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageobject',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Thumbnail Image'),
        ),
    ]
